static ip init commit

diff --git a/misc/test_ping b/misc/test_ping
--- a/misc/test_ping
+++ b/misc/test_ping
@@ -5,20 +5,44 @@ RESULT_LINES=/tmp/result_lines.txt
 MONO_LOG=/tmp/mono-log.txt
 MANIFEST=./module_manifest.json
 REPORT_FILE=/tmp/report.txt
+status=pass
 
 echo Baseline ping test report | tee -a $MONO_LOG
+if [ ! -f /scans/startup.pcap ]; then
+    echo RESULT fail base.pcap.packets startup.pcap not found | tee -a $RESULT_LINES
+    echo RESULT fail base.pcap.request startup.pcap not found | tee -a $RESULT_LINES
+    echo RESULT fail base.pcap.ack startup.pcap not found | tee -a $RESULT_LINES
+    status=fail
+else 
+    echo %% $(tcpdump -n -r /scans/startup.pcap | wc -l) packets captured. | tee -a $MONO_LOG
+    echo
 
-# This is a check that the startup.pcap file exists and is proper.
-echo
-ls -l /scans/startup.pcap
-echo %% $(tcpdump -n -r /scans/startup.pcap | wc -l) packets captured. | tee -a $MONO_LOG
-echo
-tcpdump -en -r /scans/startup.pcap ip
-echo
-tcpdump -ven -r /scans/startup.pcap port 67 | fgrep "length 1: Request"
-echo
-tcpdump -ven -r /scans/startup.pcap port 67 | fgrep "length 1: ACK"
-echo
+    if [ $(tcpdump -n -r /scans/startup.pcap | wc -l) -gt 0 ]; then
+        echo RESULT pass base.pcap.packets found packets in startup.pcap | tee -a $RESULT_LINES
+    else
+        echo RESULT fail base.pcap.packets no packets in startup.pcap | tee -a $RESULT_LINES
+        status=fail
+    fi
+
+    if [ -n "$STATIC_IP" ]; then
+        echo RESULT skip base.pcap.request static ip| tee -a $RESULT_LINES
+        echo RESULT skip base.pcap.ack static ip| tee -a $RESULT_LINES
+    else
+        req=pass
+        ack=pass
+        # This is a check that the startup.pcap file exists and is proper.
+        echo
+        tcpdump -en -r /scans/startup.pcap ip
+        echo
+        tcpdump -ven -r /scans/startup.pcap port 67 | fgrep "length 1: Request" || req=fail
+        tcpdump -ven -r /scans/startup.pcap port 67 | fgrep "length 1: ACK" || ack=fail
+        echo RESULT $req base.pcap.request | tee -a $RESULT_LINES
+        echo RESULT $ack base.pcap.ack| tee -a $RESULT_LINES
+        if [ $req = "fail" ] || [ $ack = "fail" ]; then
+            status=fail
+        fi
+    fi
+fi
 
 # Setup for accessing control plane switch. If LOCAL_IP is defined, which
 # is the intended local address for this node on the control plane then
@@ -27,9 +51,9 @@ if [ -n "$LOCAL_IP" ]; then
     echo Configuring network with local address $LOCAL_IP | tee -a $MONO_LOG
     ip addr add $LOCAL_IP dev `hostname`-eth0
     echo Switch test with port $SWITCH_PORT | tee -a $MONO_LOG
-    status=pass
-    ping -n -c 10 $SWITCH_IP || status=fail
-    echo RESULT $status base.switch.ping target %% $SWITCH_IP:$SWITCH_PORT | tee -a $RESULT_LINES
+    local_status=pass
+    ping -n -c 10 $SWITCH_IP || (local_status=fail && status=fail)
+    echo RESULT $local_status base.switch.ping target %% $SWITCH_IP:$SWITCH_PORT | tee -a $RESULT_LINES
 else
     echo LOCAL_IP not configured, assuming no network switch | tee -a $MONO_LOG
     echo RESULT skip base.switch.ping No local IP has been set, check ext_loip in system.conf | tee -a $RESULT_LINES
@@ -45,16 +69,16 @@ fi
 
 # First ping might fail b/c of warm-up delays.
 summary=""
-status=pass
-ping -n -c 10 $TARGET_IP || status=fail
+local_status=pass
+ping -n -c 10 $TARGET_IP || (local_status=fail && status=fail)
 
-if [ $status == pass ]; then
+if [ $local_status == pass ]; then
     summary="target reached"
 else
     summary="could not reach target"
 fi
 
-echo RESULT $status base.target.ping $summary %% $TARGET_IP | tee -a $RESULT_LINES
+echo RESULT $local_status base.target.ping $summary %% $TARGET_IP | tee -a $RESULT_LINES
 
 echo | tee -a $MONO_LOG
 echo Done with basic connectivity tests | tee -a $MONO_LOG
