added glinux setup script

diff --git a/bin/setup_base b/bin/setup_base
--- a/bin/setup_base
+++ b/bin/setup_base
@@ -8,6 +8,11 @@
 #
 # Docker versions after this introduced a bug that would prevent "service docker start" from working.
 DOCKER_VERSION_BASE="=18.06.1~ce~3-0"
+GLINUX=
+if [ "$1" == "glinux" ]; then
+     GLINUX="glinux"
+     shift
+fi
 
 if [ -z "$AG" ]; then
     AG="sudo apt-get -qqy --no-install-recommends"
@@ -33,22 +38,26 @@ $AG install expect lsb-release git curl sudo apt-transport-https software-proper
 retry=bin/retry_cmd
 distrib=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
 release=$(lsb_release -cs)
+DOCKER_VERSION=${DOCKER_VERSION_BASE}~${distrib}
 
 echo Installing for $distrib $release
 
-# Make sure to get a reasonably up-to-date version of OVS.
-echo "deb http://packages.wand.net.nz $release main" | sudo tee /etc/apt/sources.list.d/wand.list
-$retry sudo curl http://packages.wand.net.nz/keyring.gpg -o /etc/apt/trusted.gpg.d/wand.gpg
+if [ -n "$GLINUX" ]; then 
+     $retry bin/setup_glinux 
+else
+     $retry curl -4fsSL https://download.docker.com/linux/$distrib/gpg | sudo apt-key add -
+     sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$distrib $release stable" || true
+     # Make sure to get a reasonably up-to-date version of OVS.
+     echo "deb http://packages.wand.net.nz $release main" | sudo tee /etc/apt/sources.list.d/wand.list
+     $retry sudo curl http://packages.wand.net.nz/keyring.gpg -o /etc/apt/trusted.gpg.d/wand.gpg
 
-$retry curl -4fsSL https://download.docker.com/linux/$distrib/gpg | sudo apt-key add -
-sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$distrib $release stable" || true
+     # Hacky workaround for https://travis-ci.community/t/sometimes-build-fails-when-apt-is-updating-postgresql-apt-repository/4872/17
+     #Need to remove the || true at the end of the update line. Same as for instance above. Also in bin/setup_dev.
+     $AG update || true
+     $AG install docker-ce${DOCKER_VERSION}
+fi
 
-# Hacky workaround for https://travis-ci.community/t/sometimes-build-fails-when-apt-is-updating-postgresql-apt-repository/4872/17
-# Need to remove the || true at the end of the update line. Same as for instance above. Also in bin/setup_dev.
-$AG update || true
-
-DOCKER_VERSION=${DOCKER_VERSION_BASE}~${distrib}
-$AG install openvswitch-switch openvswitch-common docker-ce${DOCKER_VERSION}
+$AG install openvswitch-switch openvswitch-common 
 
 user=$(whoami)
 echo "Current user: $user"
