Added http authentication check, removed -F flag, removed duplicates in main colon separated dictionary, switch from Hydra to Ncrack/Medusa to avoid flakyness and to add some sort of failsafe against disconnects.

diff --git a/subset/security/password/run_password_test_for_protocol b/subset/security/password/run_password_test_for_protocol
--- a/subset/security/password/run_password_test_for_protocol
+++ b/subset/security/password/run_password_test_for_protocol
@@ -1,14 +1,14 @@
 #!/bin/bash
 
-# A test which runs a dictionary brute force attack using THC Hydra and printing out the result afterwards.
+# A test which runs a dictionary brute force attack using ncrack/medusa and printing out the result afterwards.
 # Supports http, https, telnet and ssh protocols.
-# Usage: ./run_password_test_for_protocol $TARGET_IP, $PROTOCOL, $PORT, $DICTIONARY
+# Usage: ./run_password_test_for_protocol $TARGET_IP, $PROTOCOL, $PORT, $DICTIONARY, $USERNAME_LIST, $PASSWORD_LIST
 # E.g. ./run_password_test_for_protocol 127.0.0.1 http 80 resources/dictionary.txt
 
 # Process:
 # 1. Use Nmap to check if a specific port is open, and whether the target host is down.
 # 2. If target port is open, and target host is not down, then start the brute force.
-# 3. Run the brute force command for hydra, and collect its output.
+# 3. Run the appropriate brute force command, and collect its output.
 # 4. Depending on the messages seen on the output, the test will return a specific case.
 #   - SKIP: Test was not able to run a brute force successfully due to other issues.
 #   - FAIL: Test was able to run the brute force and guess the username/password pairs.
@@ -18,6 +18,8 @@ TARGET_IP=$1
 PROTOCOL=$2
 PORT=$3
 DICTIONARY=$4
+USERNAME_LIST=$5
+PASSWORD_LIST=$6
 
 RESULT_FOLDER="reports"
 RESULT_FILE="${RESULT_FOLDER}/${PROTOCOL}_result.txt"
@@ -44,40 +46,55 @@ function is_host_down() {
   echo "$1" | grep -q "Host seems down"
 }
 
-# Runs the brute force using hydra, and returns the stdout, including stderr.
-# $1 Target IP
-# $2 Target protocol
+# Checks if http or https has authentication.
+# $1 Target protocol (HTTP or HTTPS)
+# $2 Target IP
 # $3 Target port
-# $4 Brute force dictionary
-function run_brute_force_and_get_command() {
-  if [ "$2" == "http" ]; then
-    hydra_output=$(hydra -v -I -t 4 -C $4 $1 http-get -s $3 2>&1)
-    echo "$hydra_output"
-  elif [ "$2" == "https" ]; then
-    hydra_output=$(hydra -v -I -t 4 -C $4 $1 https-get -s $3 2>&1)
-    echo "$hydra_output"
-  else
-    hydra_output=$(hydra -v -I -t 4 -C $4 $1 $2 -s $3 2>&1)
-    echo "$hydra_output"
+function does_http_or_https_have_authentication() {
+  if [[ $1 == "http" || $1 == "https" ]]; then
+    echo "$(curl -k --silent $1://$2:$3)" | grep -q "401 Authorization Required"
   fi
 }
 
-# Returns true if grep can find the success message in the hydra output.
-# $1 Hydra output
+# Runs the brute force using ncrack/medusa, and returns the output. Redirect stderr into stdout also.
+# $1 Target IP
+# $2 Target protocol
+# $3 Target port
+# $4 Colon separated brute force dictionary for medusa
+# $5 Username list for ncrack
+# $6 Password list for ncrack
+function run_brute_force_and_get_command_new() {
+  if [ "$2" == "http" ]; then
+    ncrack_output=$(ncrack --pairwise -v -U $5 -P $6 http://$1:$3 2>&1)
+    echo "$ncrack_output"
+  elif [ "$2" == "https" ]; then
+    ncrack_output=$(ncrack --pairwise -v -U $5 -P $6 https://$1:$3 2>&1)
+    echo "$ncrack_output"
+  elif [ "$2" == "ssh" ]; then
+    medusa_output=$(medusa -C $4 -h $1 -M ssh -n $3 -v 4 2>&1)
+    echo "$medusa_output"
+  elif [ "$2" == "telnet" ]; then
+    ncrack_output=$(ncrack --pairwise -v -U $5 -P $6 -T2 telnet://$1:$3 2>&1)
+    echo "$ncrack_output"
+  fi
+}
+
+# Returns true if grep can find the success message in the brute force output.
+# $1 ncrack/medusa output
 function brute_force_successful() {
-  echo "$1" | grep -q "successfully completed"
+  echo "$1" | grep -qE "Discovered credentials|\[SUCCESS\]"
 }
 
-# Returns true if grep can find the "[ERROR] <Error message>" lines in the hydra output.
-# $1 Hydra output
-function brute_force_skip() {
-  echo "$1" | grep -q "\[ERROR\]"
+# True if "timed-out/prematurely-closed" is present and their values are not zero.
+# $1 ncrack/medusa output
+function ncrack_brute_force_skip() {
+  echo "$1" | grep -oE "timed-out: [0-9]+ \| prematurely-closed: [0-9]+" | grep -qvE "timed-out: 0 \| prematurely-closed: 0"
 }
 
-# Returns true if grep can find the 0 passwords found message.
-# $1 Hydra output
-function brute_force_unsuccessful() {
-  echo "$1" | grep -q "0 valid passwords found"
+# True if ALERT or NOTICE are in the output.
+# $1 ncrack/medusa output
+function medusa_brute_force_skip() {
+  echo "$1" | grep -qE "NOTICE:|ALERT:|ERROR:|FATAL:"
 }
 
 # Writes the test result into a file.
@@ -100,8 +117,12 @@ function write_to_result_file() {
     echo "RESULT skip security.passwords.$1 Unable to connect to host." > $RESULT_FILE
   elif [ "$3" == "skip_no_port" ]; then
     echo "RESULT skip security.passwords.$1 Port $2 not open on target device." > $RESULT_FILE
-  elif [ "$3" == "skip_hydra_error" ]; then
-    echo "RESULT skip security.passwords.$1 Skipping due to hydra error, please see log." > $RESULT_FILE
+  elif [ "$3" == "skip_ncrack_error" ]; then
+    echo "RESULT skip security.passwords.$1 Skipping due to brute force issue with ncrack. Please see log." > $RESULT_FILE
+  elif [ "$3" == "skip_medusa_error" ]; then
+    echo "RESULT skip security.passwords.$1 Skipping due to brute force issue with medusa. Please see log." > $RESULT_FILE
+  elif [ "$3" == "skip_http_error" ]; then
+    echo "RESULT skip security.passwords.$1 Skipping due to http(s) server not having authentication method." > $RESULT_FILE
   fi
 }
 
@@ -113,21 +134,24 @@ echo "$NMAP_OUTPUT"
 if ! is_host_down "$NMAP_OUTPUT"; then
 
   if is_specified_port_open "$NMAP_OUTPUT" $PROTOCOL $PORT; then
-    BRUTE_FORCE_OUTPUT="$(run_brute_force_and_get_command $TARGET_IP $PROTOCOL $PORT $DICTIONARY)"
+    BRUTE_FORCE_OUTPUT="$(run_brute_force_and_get_command_new $TARGET_IP $PROTOCOL $PORT $DICTIONARY $USERNAME_LIST $PASSWORD_LIST)"
     echo "$BRUTE_FORCE_OUTPUT"
 
-    # If hydra has error messages.
-    if brute_force_skip "$BRUTE_FORCE_OUTPUT"; then
-      echo "Could not brute force due to hydra error."
-      RESULT="skip_hydra_error"
-    # If hydra can't find passwords and no errors occur.
-    elif brute_force_unsuccessful "$BRUTE_FORCE_OUTPUT" $PROTOCOL; then
-      echo "Could not brute force using dictionary."
-      RESULT="pass"
-    # If hydra finds the correct credentials and no errors occur.
-    elif brute_force_successful "$BRUTE_FORCE_OUTPUT" $PROTOCOL; then
+    if ! does_http_or_https_have_authentication $PROTOCOL $TARGET_IP $PORT; then
+      echo "Will not start brute force as http(s) server has no authentication."
+      RESULT="skip_http_error"
+    elif ncrack_brute_force_skip "$BRUTE_FORCE_OUTPUT"; then
+      echo "Could not brute force due to an issue with ncrack at runtime. Please check log."
+      RESULT="skip_ncrack_error"
+    elif medusa_brute_force_skip "$BRUTE_FORCE_OUTPUT"; then
+      echo "Could not brute force due to an issue with medusa at runtime. Please check log."
+      RESULT="skip_medusa_error"
+    elif brute_force_successful "$BRUTE_FORCE_OUTPUT"; then
       echo "Was able to brute force using dictionary."
       RESULT="fail"
+    else
+      echo "Could not brute force using dictionary."
+      RESULT="pass"
     fi
 
   else
