Updating build cmds

diff --git a/cmd/build b/cmd/build
--- a/cmd/build
+++ b/cmd/build
@@ -7,7 +7,7 @@ if [ "$1" == help ]; then
  echo $0 push : Pushes images to docker hub
  echo $0 pull : Pulls images from docker hub
  echo $0 build : Builds missing docker images
- echo $0 force : Builds all docker images
+ echo $0 force [version] : Builds all docker images
  exit 0
 fi
 
@@ -15,9 +15,14 @@ fi
 set -o pipefail
 
 ROOT=$(dirname $0)/..
+VERSION=`git describe`
 
 inline=
 DOCKER_IMAGE_LIST=docker_images.txt
+DOCKER_IMAGE_VER=docker_images.ver
+
+# Clear out version to enforce build flow.
+rm -f inst/$DOCKER_IMAGE_VER
 
 cd $ROOT
 source misc/config_base.sh
@@ -33,22 +38,28 @@ function pull_images {
             echo Skipping $image pull 
             continue
         fi 
-        echo Pulling $image:$hash from dockerhub...
-        (docker pull $image:$hash && docker tag $image:$hash $image:latest) || echo "Could not pull $image:$hash."
+        echo Pulling $image:$VERSION from dockerhub...
+        (docker pull $image:$VERSION && docker tag $image:$VERSION $image:latest) || echo "Could not pull $image:$VERSION."
     done 
 }
 
 if [ "$1" == push ]; then
+    if [ ! -f inst/$DOCKER_IMAGE_VER ]; then
+	echo Missing build version file, do force build with desired version.
+	false
+    fi
+    NEWVER=$(< inst/$DOCKER_IMAGE_VER)
     cat inst/$DOCKER_IMAGE_LIST | while read image hash other; do
-        found=$(docker images $image | awk '{print $3}' | grep $hash) || echo ""
+        found=$(docker images $image | awk '{print $3}' | grep $hash) || true
         if [ -z "$found" ]; then
             echo $image:$hash not found locally...
             continue
         fi
-        echo Push $image:$hash to dockerhub...
-        bin/docker_push $image $hash
+	docker tag $image:$hash $image:$NEWVER
+        echo Push $image:$NEWVER to dockerhub...
+        bin/docker_push $image $NEWVER
     done
-    echo Updating misc/$DOCKER_IMAGE_LIST
+    echo Updating misc/$DOCKER_IMAGE_LIST for version $NEWVER
     cp inst/$DOCKER_IMAGE_LIST misc/$DOCKER_IMAGE_LIST
     echo Done with docker build push.
     exit 0
@@ -64,9 +75,15 @@ elif [ "$1" == check ]; then
     bin/build_hash check
     exit 0
 elif [ "$1" == force ]; then
+    if [ -n "$2" ]; then
+	echo Setting build version to $2
+	echo $2 > inst/$DOCKER_IMAGE_VER
+    fi
     force=force
     shift
 fi
+
+rm -f inst/$DOCKER_IMAGE_LIST
 
 if [ "$1" == inline ]; then
     inline="inline"
@@ -92,7 +109,6 @@ fi
 
 bin/docker_build $force $inline
 
-rm inst/$DOCKER_IMAGE_LIST || true
 echo Updating inst/$DOCKER_IMAGE_LIST...
 docker images | sort | fgrep daqf/ | fgrep latest | while read image tag hash other; do
     echo $image $hash >> inst/$DOCKER_IMAGE_LIST
